### ISSUE TITLE
The transparent keyword doesn't autocomplete

### ISSUE THREAD

**Issue by LandonSchropp** [atom/language-sass#100]
Please let me know if this isn't the right place to post this and I'll close this ticket.

On my local machine, I can't seem to autocomplete the `transparent` keyword. Instead, I end up with `transparentize`.

<img width="606" alt="screen shot 2016-01-26 at 1 12 20 pm" src="https://cloud.githubusercontent.com/assets/361591/12595178/ba8cbf74-c42e-11e5-81d4-ff67d45da24d.png">

I'm using Atom 1.4.0 and language-sass 0.45.0 on OS X 10.11.1.

**Comment by 50Wliu** [comment]
@LandonSchropp I *think* you want autocomplete-css instead (which handles Less/Sass as well).

**Comment by LandonSchropp** [comment]
@50Wliu Gotcha, thanks for pointing me in the right direction.
