### ISSUE TITLE
Lines underneath media query block are not colored

### ISSUE THREAD

**Issue by Knifa** [atom/language-sass#103]
Using Atom 1.7.1 and language-sass 0.46.0.

Lines underneath media queries don't get colored correctly until the next block.

![image](https://cloud.githubusercontent.com/assets/622619/14622718/f740dfaa-05c3-11e6-83fa-e84d1f193595.png)

**Comment by 50Wliu** [comment]
This is actually a duplicate of #79 - feel free to subscribe there for updates.
