### ISSUE TITLE
error BASH_FUNC_module

### ISSUE THREAD

**Issue by cortopy** [atom/language-sass#120]
I just upgraded to Atom 1.7.3 and currently I need to disable language-sass, otherwise I get the following error

```
Error: /usr/bin/bash: module: line 1: syntax error: unexpected end of file /usr/bin/bash: error importing function definition for BASH_FUNC_module' /usr/bin/bash: scl: line 1: syntax error: unexpected end of file /usr/bin/bash: error importing function definition forBASH_FUNC_scl'
```

Oddly, this error happens with scss files but not with sass indented syntax

Atom: 1.7.3
Node: 0.10, 5.11 and 6
OS: Fedora 23

**Comment by 50Wliu** [comment]
I don't believe this is a problem with language-sass as it doesn't use Bash.  I would check your other packages ([package-cop](https://atom.io/packages/package-cop) is generally a good way to do this).

**Comment by cortopy** [comment]
Thanks @50Wliu package-cop did the trick. It was the linter
