### ISSUE TITLE
CSS Feature queries are mistakenly highlighted as syntax errors

### ISSUE THREAD

**Issue by albell** [atom/language-sass#125]
For example:

![bad-supports-error-highlighting-in-atom](https://cloud.githubusercontent.com/assets/1142025/15332509/be42b67a-1c1a-11e6-9284-21d254e5e1cc.png)

The highlighting for a similar snippet tagged as a CSS file shows as expected:

![screen shot 2016-05-17 at 10 33 57 am](https://cloud.githubusercontent.com/assets/1142025/15332548/eaa72764-1c1a-11e6-9aa1-b73bd1915d19.png)

Note that (nested) feature queries are <a href="https://github.com/sass/libsass/pull/626">fully supported</a> in SCSS as of a couple years ago. Would be nice to see this error go away. Thanks.

**Comment by esdoppio** [comment]
Actually, `language-css` also doesn't get it right, `@supports` and the condition are tokenized as selectors.
