### ISSUE TITLE
enforce a line length limit in source?

### ISSUE THREAD

**Issue by albell** [atom/language-sass#127]
I'm counting over 5200 characters (!) on a single line of source of scss.cson, in property_name.match.

This is arguably error prone. At the very least, it's hard to read diffs, especially in the browser. Not super contributor-friendly.

Would it make sense to break these properties into concatenated strings on separate lines? Or a big template string?

**Comment by 50Wliu** [comment]
Yes, this would be helpful.  I plan on doing it once I get some of my existing language-sass PRs tested out and merged so as to avoid conflicts.

```cson
'match': '''(?x)
  line 1...
  line 2...
'''
```

**Comment by yogasaikrishna** [comment]
I will do it. What should be the optimal length for the line?

**Comment by 50Wliu** [comment]
Whatever you think is reasonable should work.

**Comment by yogasaikrishna** [comment]
How about keeping each property in a separate line. I think it will have better readability (downside is it will increase number of lines)

```cson
'match': '''\\b(
    a|
    abbr|
    acronym|
    b|
    base|
    dbi
)\\b'''
```
 or we can keep all properties starting with same letter on one line like

```cson
'match': '''\\b(
    a|abbr|acronym|
    b|base|dbi
)\\b'''
```

**Comment by esdoppio** [comment]
the second one sounds better. And you need to put `(?x)` (extended mode) in front of the pattern to make it ignore whitespace:

```
'match': '''(?x)
…
'''
```

Try looking at the surrounding code first and keep things (like indentation, placement) consistent 😉
