### ISSUE TITLE
Missing CSS properties

### ISSUE THREAD

**Issue by kirkas** [atom/language-sass#128]
I've noticed few missing CSS properties:

- align-items
- text-size-adjust
- resize
- appearance
- tap-highlight-color
- justify-content
- background-position-x
- background-position-y
- word-break
- flex
- flex-basis
- flex-direction
- flex-flow
- flex-grow
- flex-shrink
- flex-wrap
- pointer-events

**Comment by 50Wliu** [comment]
On the latest master only the following are missing in `sass.cson`:
* text-size-adjust
* resize
* appearance
* tap-highlight-color
* background-position-x
* background-position-y
* pointer-events

And `scss.cson`:
* text-size-adjust
* background-position-x
* background-position-y

**Comment by esdoppio** [comment]
* `tap-highlight-color` is not in the standard yet, not even a proposed property.
* `text-size-adjust` is still in the draft, and only implemented in iOS Safari.

Maybe these two can wait.
