### ISSUE TITLE
improper scoping of code for theming

### ISSUE THREAD

**Issue by smlombardi** [atom/language-sass#129]
see https://github.com/Briles/gruvbox-atom/issues/3

- note the first 3 commas on color and the last is white.
- The alpha value in the rgba color is magenta if it's 0 but green if its something else.
- hyphenated propetry in transition has a magenta hyphen
- the digit in the transition timing is white while other digits in property values are magenta.

![862c4efa-27fe-11e6-9863-7f3eb0c99aa4](https://cloud.githubusercontent.com/assets/835148/15727402/2325a43e-2824-11e6-9369-51f34917a79b.png)

from the theme author: 

> Unfortunately these are a result of improper syntax scoping and would best be fixed by the maintainers of Atom's syntaxes.

> - the commas should be white, but not all of them are scoped so I can't color them consistently
> - Certain RGB Alpha values are given an incorrect variable.parameter.url.scss scope. This scope is correctly colored green, but should not be applied in this instance.
> - The hyphen is scoped as support.constant.mathematical-symbols.scss which is correctly colored as purple, but again, improperly scoped.
> - Numbers in this case are not given any scope, so I can't color them.
> - For cases like this I typically mask the improper scoping but for these specific cases I cannot because of the lack of scope specificity.

**Comment by 50Wliu** [comment]
I have most of these fixed locally except for the `transition` property name highlighting.  That's a bit more difficult than the rest.

**Comment by smlombardi** [comment]
Looking forward to this

**Comment by 50Wliu** [comment]
Was on vacation and just got back.  Will try to finish this in the next few days.
