### ISSUE TITLE
Bug: incorrect highlight on the next block when there's no trailing semicolon

### ISSUE THREAD

**Issue by dustindowell22** [atom/language-sass#140]
I'm using `sass-linter` to enforce no trailing semicolons. However I encountered this highlighting bug. This is valid SCSS syntax. I'm positive that this is a bug with Atom's highlighter and not the linter.

![img](http://f.cl.ly/items/430H3A1M3Q2W2o1j1d1m/Screen%20Shot%202016-06-19%20at%2011.49.00%20AM.png)

**Comment by 50Wliu** [comment]
This should be fixed in either Atom 1.9.0 or 1.10.0.
