### ISSUE TITLE
viewport units are not highlighted

### ISSUE THREAD

**Issue by controversial** [atom/language-sass#143]
Though units like `px` are highlighted with the number:  ![screenshot 2016-06-27 at 8 38 44 pm](https://cloud.githubusercontent.com/assets/10377391/16400197/3a9b09b4-3ca7-11e6-9bea-1ea42131ae32.png) viewport units are not: ![screenshot 2016-06-27 at 8 38 50 pm](https://cloud.githubusercontent.com/assets/10377391/16400195/38b67fa2-3ca7-11e6-8447-d286bab7929f.png)

I'm using the `.sass` tab-indented syntax instead of the `.scss` syntax, if that makes a difference

**Comment by 50Wliu** [comment]
This works for me using language-sass@0.55.0, so I assume this has been fixed.  You should start seeing proper highlighting in Atom 1.10.0.

**Comment by controversial** [comment]
Ok. I'm on 1.7.4 now. 1.10 seems like a long way off...
