### ISSUE TITLE
: is not tokenized as part of a pseudo-class

### ISSUE THREAD

**Issue by esdoppio** [atom/language-sass#145]
`:` is part of a pseudo-class, as in https://drafts.csswg.org/selectors-3/#pseudo-classes, 

> A pseudo-class always consists of a "colon" (:) followed by the name of the pseudo-class and optionally by a value between parentheses.

It should be tokenized accordingly, but right now (v0.55.0) it is not:

https://github.com/atom/language-sass/blob/master/spec/scss-spec.coffee#L308-L311

**Comment by 50Wliu** [comment]
I feel like I was the one who explicitly changed it to not be part of the pseudo-class...whoops.

**Comment by esdoppio** [comment]
Wanna fix it yourself?

**Comment by 50Wliu** [comment]
Sure.
