### ISSUE TITLE
Sass property syntax is not well supported

### ISSUE THREAD

**Issue by esdoppio** [atom/language-sass#151]
This is one way of declaring properties in Sass, by placing `:` before the property name:

``` sass
#main
  :color blue
  :font-size 0.3em
```
- The colon is not tokenized
- The property names are tokenized as selectors:

![image](https://cloud.githubusercontent.com/assets/18070858/16705395/4bbfd220-45bb-11e6-917b-53c525b00fb5.png)

**Comment by esdoppio** [comment]
In `sass.cson`, for properties, the whole key-value pair is tokenized as `meta.property-name.sass` (which makes no sense), whereas in `scss.cson`, only the key part is tokenized as `meta.property-name.scss`.

Should we change `meta.property-name.sass` to `meta.property.sass`?

**Comment by 50Wliu** [comment]
Just to make sure we're on the same page:
```
.something
  color:          red          < This whole line: property-list
  ^^^^^           ^^^
  property-name   property-value
```

Similarly...
```
.something
  :color          red          < This whole line: property-list
   ^^^^^          ^^^
   property-name  property-value

**Comment by esdoppio** [comment]
How about:

```sass
	color:			red
 // ^^^^^^      	^^^				line: property
 // property-name	property-value
```

or

```sass
	color:			red
 // ^^^^^^      	^^^				line: NO-NAME
 // property-name	property-value

**Comment by 50Wliu** [comment]
Getting back to this late, but yes, :+1: for the second one (with the exception that the `:` is also tokenized as property-value).
