### ISSUE TITLE
Alpha floats in color values in functional notation highlight incorrectly.

### ISSUE THREAD

**Issue by albell** [atom/language-sass#155]
![scss](https://cloud.githubusercontent.com/assets/1142025/17069712/f44743fa-500c-11e6-84c6-258b4038b221.png)

For reference, in language-css:
![css](https://cloud.githubusercontent.com/assets/1142025/17069713/f6c83dfa-500c-11e6-9306-1e7ab4de88b9.png)

In other words, the "0.5" values should be blue.

**Comment by 50Wliu** [comment]
This has been fixed and will be out in Atom 1.10.0.

**Comment by albell** [comment]
Great, thank you.
