### ISSUE TITLE
comments inside keyframe declarations highlight incorrectly

### ISSUE THREAD

**Issue by albell** [atom/language-sass#157]
![comments-inside-keyframes](https://cloud.githubusercontent.com/assets/1142025/17259211/4cb16ff8-557f-11e6-9996-0f5be22c3e48.png)

**Comment by esdoppio** [comment]
The problem arises coz the outer block is no tokenized as `meta.property-list.scss` in which the comment rule is included. We can fix this with a simple patch to `#at_rule_keyframes`, but considering the rule is kinda messy and bloated, I think we should rewrite it instead.
