### ISSUE TITLE
Improper parsing of numeric values for `transition` property

### ISSUE THREAD

**Issue by adambuczynski** [atom/language-sass#159]
Ref https://github.com/atom/language-css/issues/58

Maybe it's not just `transition` that's affected, but I seem to only notice it there:

![image](https://cloud.githubusercontent.com/assets/490562/15802998/4bc53e18-2b1c-11e6-94a3-c5abbfe2f463.png)

The `.2` is not marked as `constant.numeric` but it should be:

![image](https://cloud.githubusercontent.com/assets/490562/15803001/61edd88a-2b1c-11e6-8c03-29f54a2da74a.png)

The leading `0` is properly marked:

![image](https://cloud.githubusercontent.com/assets/490562/15803006/70f0d490-2b1c-11e6-9937-b3b93c9794a0.png)

**Comment by 50Wliu** [comment]
Cannot reproduce using language-sass@1831686592ddc4ae216d1b0bce19e34ef472671d.
