### ISSUE TITLE
Support for shorthand numeric values

### ISSUE THREAD

**Issue by adambuczynski** [atom/language-sass#160]
Ref: https://github.com/atom/language-css/issues/57

Shorthand for `0.3` which is often used is simply `.3`. However, the language grammar doesn't pick this up properly and doesn't mark the leading `.` as `constant.numeric`:

![image](https://cloud.githubusercontent.com/assets/490562/15802990/cf0b9ebc-2b1b-11e6-8618-651043bde810.png)

**Comment by 50Wliu** [comment]
Cannot reproduce using language-sass@1831686592ddc4ae216d1b0bce19e34ef472671d.

**Comment by adambuczynski** [comment]
Is the latest `language-sass` in Atom master branch already?

**Comment by 50Wliu** [comment]
Not yet, but I'm planning to do another language update roundup shortly.

**Comment by adambuczynski** [comment]
Excellent, thanks. I'll re-test the issues when those new versions are in.
