### ISSUE TITLE
[Sass] Some properties with dashes aren't color formatted correctly

### ISSUE THREAD

**Issue by SpectralKH** [atom/language-sass#161]
As you see with the first 4 properties, they are correct. However, with the 3 last ones, the whole line turns into one color.

![screen shot 2016-08-05 at 3 08 07 pm](https://cloud.githubusercontent.com/assets/11315492/17437522/6fd6b6d8-5b1e-11e6-9e44-5c59319f30a3.png)

Note that the pictures properties are not wrongly formatted in 0.56.0. Here are the ones that do turn pink:

```
background-blend-mode:
border-image-outset:
border-image-repeat:
border-image-slice:
border-image-source:
border-image-width:
line-break:
text-combine-upright:
text-decoration-color:
text-decoration-line:
text-decoration-style:
text-underline-position:
font-feature-settings:
font-kerning:
font-language-override:
font-synthesis:
font-variant-alternates:
font-variant-caps:
font-variant-east-asian:
font-variant-ligatures:
font-variant-numeric:
font-variant-position:
text-orientation:
text-combine-upright:
writing-mode:
perspective-origin:
transform-origin:
transform-style:
ime-mode:
nav-index:
text-overflow:
image-rendering:
mask:
mask-type:
mark:
mark-after:
mark-before:
phonemes:
voice-pitch-range:
marquee-play-count:
marquee-style
```

**Comment by SpectralKH** [comment]
List of all properties that have their lines turn pink:

`background-blend-mode:
background-clip:
background-origin:
border-image:
border-image-outset:
border-image-repeat:
border-image-slice:
border-image-source:
border-image-width:
box-decoration-break:
align-content:
align-items:
align-self:
flex:
flex-basis:
flex-direction:
flex-flow:
flex-grow:
flex-shrink:
flex-wrap:
justify-content:
order:
hanging-punctuation:
hyphens:
line-break:
overflow-wrap:
tab-size:
text-align-last:
text-combine-upright:
text-justify:
word-break:
word-wrap:
text-decoration-color:
text-decoration-line:
text-decoration-style:
text-underline-position:
@font-face:
@font-feature-values:
font-feature-settings:
font-kerning:
font-language-override:
font-synthesis:
font-variant-alternates:
font-variant-caps:
font-variant-east-asian:
font-variant-ligatures:
font-variant-numeric:
font-variant-position:
text-orientation:
text-combine-upright:
writing-mode:
@keyframes:
animation-delay:
animation-direction:
animation-duration:
animation-fill-mode:
animation-iteration-count:
animation-name:
animation-play-state:
animation-timing-function:
backface-visibility:
perspective-origin:
transform-origin:
transform-style:
transition-property:
transition-duration:
transition-timing-function:
transition-delay:
ime-mode:
nav-down:
nav-index:
nav-left:
nav-right:
nav-up:
outline-offset:
resize:
text-overflow:
break-after:
break-before:
break-inside:
column-count:
column-fill:
column-gap:
column-rule:
column-rule-color:
column-rule-style:
column-rule-width:
column-span:
column-width:
columns:
filter:
image-orientation:
image-rendering:
image-resolution:
object-fit:
object-position:
mask:
mask-type:
mark:
mark-after:
mark-before:
phonemes:
rest:
rest-after:
rest-before:
voice-balance:
voice-duration:
voice-pitch:
voice-pitch-range:
voice-rate:
voice-stress:
voice-volume:
marquee-direction:
marquee-play-count:
marquee-speed:
marquee-style:`

**Comment by albell** [comment]
+1

**Comment by szimek** [comment]
One more that doesn't work properly is `text-size-adjust`.

**Comment by 50Wliu** [comment]
All of these should be highlighted if you're using Atom 1.17.0.
