### ISSUE TITLE
auto indent doesn't work on Atom

### ISSUE THREAD

**Issue by dirago** [atom/language-sass#166]
Hi all,

I'm trying to figure it out why Atom doesn't want to auto-indent a sass file..

I've got Emmet and the package language-sass but when i start a new line, the cursor always returns to the beginning. I have to auto-indent by myself each time.

Anybody have this problem?

**Comment by dirago** [comment]
I just read previous issues on this problem (my bad), in fact we always have to indent manually all the first property below each selector?

**Comment by 50Wliu** [comment]
Auto-indentation for `.sass` files is now included starting in Atom 1.10.0-beta0.
