### ISSUE TITLE
CSS variable names are highlighted as erroneous code

### ISSUE THREAD

**Issue by beingmrkenny** [atom/language-sass#168]
### Description

CSS variable names are highlighted as an error when in fact they are valid CSS, regardless of what syntax theme you are using.
### Steps to Reproduce
1. Define a CSS variable in the form `--variable-name: value;`

**Expected behavior:**

The variable name should look like a variable.

**Actual behavior:**

The variable name looks like an error (red background in this theme):

![syntax](https://cloud.githubusercontent.com/assets/2005857/18001101/14f47b68-6b79-11e6-9d0e-c316843584c6.png)
### Versions

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

OS X 10.11.6 (15G31)

**Comment by 50Wliu** [comment]
You're on a very outdated version of Atom - the latest version is currently 1.9.9 and has some fixes for what you're seeing.

**Comment by beingmrkenny** [comment]
Good spot, had automatic updates switched off for some reason.

Updated to 1.9.9 and still seeing the same issue.

**Comment by 50Wliu** [comment]
Sorry, should have clarified.  By "currently", I meant the latest version of language-sass, which isn't in any released Atom version yet.

**Comment by 50Wliu** [comment]
This has been fixed in master, thanks to #195.

**Comment by beingmrkenny** [comment]
Do you know when this will make it into a release?

**Comment by 50Wliu** [comment]
Should be Atom 1.16.  It just missed making it into 1.15.
