### ISSUE TITLE
Auto-indentation bug

### ISSUE THREAD

**Issue by controversial** [atom/language-sass#173]
#115 introduced auto-indentation, which is awesome. However, there's a small bug in the grammar, pressing enter after an `@import` line causes the next line to become auto-indented. I don't know of any features involving indentation after an `@import`, so I'm pretty sure this is a bug.

@50Wliu

**Comment by 50Wliu** [comment]
Thanks for the report!

**Comment by controversial** [comment]
There's actually another one as well, @50Wliu:

- Open a `.sass` file
- Press `tab`
- Press enter, and continue pressing enter

Indentation occurs after blank lines with just whitespace. Each time you press enter, the indent level goes up.

This is because your regex is missing a case for whitespace-only lines. Perhaps it should check that the line contains non-whitespace characters.

**Comment by controversial** [comment]
Bug number 3: Auto-indent is triggered when pressing enter after a comma.

**Comment by controversial** [comment]
Cool, thanks. Will this be in 1.11 or 1.12?

**Comment by 50Wliu** [comment]
Probably 1.12.0, but no guarantees.
