### ISSUE TITLE
Length units inside feature query tests are mistakenly highlighted as errors

### ISSUE THREAD

**Issue by albell** [atom/language-sass#176]
![feature-queries-css](https://cloud.githubusercontent.com/assets/1142025/18729954/c7c7b9b4-8008-11e6-8ec0-0616298dc3dd.png)
![feature-queries-scss](https://cloud.githubusercontent.com/assets/1142025/18729960/ca690b50-8008-11e6-800f-66cbe6428ff8.png)

**Comment by 50Wliu** [comment]
Cannot reproduce using ae249e5, assuming fixed.
