### ISSUE TITLE
Update tag names in accordance with W3C specifications?

### ISSUE THREAD

**Issue by idbartosz** [atom/language-sass#179]
IMHO we should consider to follow W3C references since there's some inconsequence and trash in our grammars, e.g. in _sass.cson_ there are **131** tags in `entity.name.tag.css.sass` while W3C defines: 
**108** - HTML 
**6** - SVG 1.1 
**1** - SVG 2 
**31** - MathML

We should keep our tag list:
1. as it is,
2. update to W3C,
1. HTML,
2. HTML + SVG,
3. HTML + SVG + MathML,
4. other ideas.

What do you think?

**Comment by thomasjo** [comment]
Wouldn't this necessitate updating attributes as well?

**Comment by idbartosz** [comment]
Tags were an example, it would also apply to attributes in the long run.
