### ISSUE TITLE
Custom tag highlighted incorrectly when using attribute selector

### ISSUE THREAD

**Issue by code-tree** [atom/language-sass#189]
![image](https://cloud.githubusercontent.com/assets/11289719/20639305/030191ae-b3f2-11e6-8ec0-62911fa843dc.png)

Note: md-toolbar is fine when has no attribute selector

**Comment by 50Wliu** [comment]
```scss
md-toolbar[color='primary' .secondary { }
```

**Comment by 50Wliu** [comment]
This appears to be somewhat fixed, now `md-toolbar` receives no tokens rather than invalid tokens.
