### ISSUE TITLE
Valid @import syntax falsely highlighted as an error

### ISSUE THREAD

**Issue by lope** [atom/language-sass#190]
To reproduce, simply paste this into a new **SCSS** file (not SASS)

```scss
@mixin prefix($declarations, $prefixes: ()) {
 @each $property, $value in $declarations {
  @each $prefix in $prefixes {
   #{'-' + $prefix + '-' + $property}: $value;
  }
  #{$property}: $value;
 }
}


.cssSpinner {
 > div:nth-of-type(1)  { @include prefix(( transform:rotate(0deg)   translate(0,-60px), animation-delay:-0.5s   ), webkit); }
}

```

The `translate` command and it's parameters are falsely highlighted as an error.

**Comment by 50Wliu** [comment]
Cannot confirm on master, assuming fixed.

**Comment by lope** [comment]
Hi, I've updated to the latest version of atom, and now it's not highlighting translate anymore, but it is highlighting webkit.

For example
`@include prefix ((user-select: none), webkit khtml moz ms);`
highlights webkit khtml moz ms

**Comment by 50Wliu** [comment]
I specifically said master and not the latest version of Atom because there are certain changes on master that have not yet been included in any released versions of Atom yet.

**Comment by lope** [comment]
Ok thanks.

Some questions if you don't mind :)

* What's the most efficient way to install the master version?
* Should I uninstall the current version then install this one?
* What's the best way to bundle this into a package format?
* Is there a way to do it so that I can seamlessly upgrade when a newer version is released?

**Comment by 50Wliu** [comment]
> What's the most efficient way to install the master version?

There's a variety of ways, some of which may appeal more to you than others:
1. Manually clone this repository into the `~/.atom/packages` folder.
2. Clone this repository somewhere else and execute the `apm link` command inside the repository.
3. `apm dev language-sass` (which clones into `~/github` by default), and then start Atom using `atom --dev`.
4. Copy-paste `https://github.com/atom/language-sass` into the Install section of the Settings View.

However, manually installing bundled packages is highly unrecommended - don't expect any support if you do so, and if you decide to, definitely remember to uninstall it once a version of Atom is released containing the features/bug fixes you want.

> Should I uninstall the current version then install this one?

First of all, manually installed packages automatically override bundled versions.  However, I would recommend that you don't manually install.

> What's the best way to bundle this into a package format?

Can you elaborate on this question?

> Is there a way to do it so that I can seamlessly upgrade when a newer version is released?

Not really, no, though the 4th option above is probably the closest you'll get.

I'm going to release a new version of this soon that should make it into Atom 1.14.0.  1.14.0 betas should be out sometime in January, but no guarantees.
