### ISSUE TITLE
Wrong variable highlighting in complex selectors

### ISSUE THREAD

**Issue by julmot** [atom/language-sass#193]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using a variable inside brackets looks good in CSS properties or selectors, e.g.:

![selectors](https://cloud.githubusercontent.com/assets/8310677/21679666/8d6791be-d345-11e6-8deb-79b08e719fe2.png)

But not in e.g. `:nth-child` selectors:

![in-brackets](https://cloud.githubusercontent.com/assets/8310677/21679673/9c6bd328-d345-11e6-856c-af947ef92513.png)

Or e.g.:

![complex2](https://cloud.githubusercontent.com/assets/8310677/21680011/4f19a92c-d347-11e6-81d6-a32a521cc096.png)

### Versions
- Windows 7
- 
  ```bash
  Atom    : 1.12.9
  Electron: 1.3.13
  Chrome  : 52.0.2743.82
  Node    : 6.5.0
  ```

**Comment by 50Wliu** [comment]
```scss
.test {
	&:nth-child(#{$j}) {
		// stuff
	}
}

.test2 {
	&[cla#{$i}^="test"] {
		
	}
}
```
