### ISSUE TITLE
fractional number highlighting issue

### ISSUE THREAD

**Issue by aeschli** [atom/language-sass#196]
```scss
$ease-out: cubic-bezier(0, 0, 0.2, 1);
```
![image](https://cloud.githubusercontent.com/assets/6461412/22696548/aaee0b32-ed4e-11e6-8453-c5f8be5b5b8e.png)

Note that `0.2` gets funny colors.
It gets scopes
constant.numeric.color.rgb-value.scss, variable.parameter.url.scss, punctuation.separator.delimiter.scss

**Comment by 50Wliu** [comment]
I wonder if it's worth keeping the hex-value and rgb-value specific stuff around instead of just applying generic numeric highlighting to everything.
