### ISSUE TITLE
Add support for CSS Custom Properties

### ISSUE THREAD

**Issue by bsmith-cycorp** [atom/language-sass#206]
CSS Custom Properties in SCSS files are currently highlighted as errors:

<img width="394" alt="style_scss_ ___git_cyc-adaptable-toolset" src="https://cloud.githubusercontent.com/assets/25161635/25250991/64a953d0-25dd-11e7-90d2-988f11cd92c2.png">

More details on Custom Properties:
[CSS Custom Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*)

**Comment by 50Wliu** [comment]
Please update to the latest Atom version.  This was added in Atom 1.16.0.

**Comment by bsmith-cycorp** [comment]
Hmm. I checked for updates, and Atom said 1.13.1 was the latest version. Guess that's a bug for a different repo.
