### ISSUE TITLE
Missing CSS selectors?

### ISSUE THREAD

**Issue by eivindml** [atom/language-sass#210]
Looks like there are some missing CSS selectors regarding the css grid property. A lot of stuff around grids are highlighted incorrectly. 

<img width="487" alt="screen shot 2017-05-14 at 10 39 19" src="https://cloud.githubusercontent.com/assets/202450/26032351/a1c17ccc-3891-11e7-8a69-39647bd736d1.png">

**Comment by 50Wliu** [comment]
The CSS property names are inherited from language-css, so would you mind filing an issue there instead?

**Comment by eivindml** [comment]
Issue filed here: https://github.com/atom/language-css/issues/116

**Comment by eivindml** [comment]
Looks like it's already added. To `language-css`. https://github.com/atom/language-css/pull/96 (both `grid-gap` and `grid-template-columns` was added.)

Not sure why the syntax highlight is showing up incorrectly.

**Comment by 50Wliu** [comment]
Then that probably means it hasn't been added to the stable version of Atom yet.

**Comment by 50Wliu** [comment]
Took a look and these properties should be properly highlighted starting with Atom 1.17.0, which was released a week ago.
