### ISSUE TITLE
backdrop-filter support

### ISSUE THREAD

**Issue by aleclarson** [atom/language-sass#216]
The `backdrop-filter` property is highlighted as an error.

I'm on v0.57.1, is this fixed in a newer version?

I noticed v0.59 is released, but I cannot update using Atom.

**Comment by 50Wliu** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter) says that the `backdrop-filter` property is still experimental, and the specification itself is still an Editor's Draft.  Furthermore, none of the major browsers implement an unprefixed version of the keyword.  Therefore, I don't think that we will be adding support for `backdrop-filter` until such a time when the specification has standardized and/or browsers start supporting it.
