### ISSUE TITLE
Incorrect syntax highlighting for `:not()` selectors

### ISSUE THREAD

**Issue by Rockster160** [atom/language-sass#229]
### Description

Syntax highlighting for `:not()` selector is off, and breaks highlighting for immediately following selectors.

### Steps to Reproduce
1. Use the `:not()` selector, regardless of attachment to any other selectors.

**Expected behavior:** Highlight the same way other computed selectors do:
<img width="163" alt="screen shot 2017-07-21 at 8 03 41 pm" src="https://user-images.githubusercontent.com/8505362/28487541-0151068c-6e50-11e7-9392-05435c887883.png">

**Actual behavior:** 
<img width="161" alt="screen shot 2017-07-21 at 8 07 03 pm" src="https://user-images.githubusercontent.com/8505362/28487548-32a6e580-6e50-11e7-8e87-3c0bf0807f01.png">

### Versions
```
Atom: 1.18.0
language-sass: 0.59.0
```

**Comment by 50Wliu** [comment]
Fixed by #222.
