### ISSUE TITLE
`cursor` property has missing scope

### ISSUE THREAD

**Issue by adamreisnz** [atom/language-sass#235]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![image](https://user-images.githubusercontent.com/490562/31791814-6103d740-b576-11e7-858f-28e2da17aec9.png)

**Expected behavior:**
For `cursor` to have normal property highlighting, e.g. scope `meta.property-name.scss`

![image](https://user-images.githubusercontent.com/490562/31791852-88dabb6c-b576-11e7-88b0-4967659f1bf1.png)

**Actual behavior:** [What actually happens]
Doesn't have it.

![image](https://user-images.githubusercontent.com/490562/31791832-772af9f4-b576-11e7-9ce2-8321896e6b48.png)

**Reproduces how often:** 
100%

### Versions
Atom    : 1.21.0-dev-be3dbab49
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.1
OS X

**Comment by 50Wliu** [comment]
Fixed by #234.
