### ISSUE TITLE
:not() pseudoselector breaks coloring

### ISSUE THREAD

**Issue by paddotk** [atom/language-sass#240]
When using the :not() pseudoselector (e.g. `.classname1:not(.classname2) { }`) the coloring of the stuff after it, until the closing bracket, is wrong, seemingly because the package doesn't recognize this as valid SCSS. See screenshot.

![sass](https://user-images.githubusercontent.com/11683974/32225893-3b2c3b78-be47-11e7-977b-79091465eaed.png)

I'd much appreciate support for this could be added!

**Comment by 50Wliu** [comment]
Looks like this got fixed somewhere along the way.
![scss-not](https://user-images.githubusercontent.com/2766036/32230609-daf88538-be53-11e7-9c9d-c7f08fb713e8.png)

**Comment by paddotk** [comment]
@50Wliu Not sure what you mean? My package is up-to-date.

**Comment by 50Wliu** [comment]
Atom's bundled packages do not automatically update and are updated when Atom itself is updated.  So this issue will most likely be fixed when Atom 1.22.0 is released.

**Comment by paddotk** [comment]
Ah ok, thanks. Will wait for the new Atom then :)
