### ISSUE TITLE
[SCSS] Wrong tokenization of @extend rule

### ISSUE THREAD

**Issue by octref** [atom/language-sass#272]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

![image](https://user-images.githubusercontent.com/4033249/67245472-e202d000-f410-11e9-925c-6169ce6cc325.png)

### Steps to Reproduce

On this SCSS file:

```scss
.foo {
  @extend .foo-bar-baz;
}
```

Put cursor before `-bar`, and use command "Editor: Log Cursor Syntax Tree Scope"

**Expected behavior:**

Should be tokenized as selector.

**Actual behavior:**

Tokenized as `support.constant.mathematical-symbol.scss`

**Reproduces how often:**

100%

### Versions

Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

**Comment by octref** [comment]
Originally reported at https://github.com/microsoft/vscode/issues/64304

**Comment by rsese** [comment]
Thanks @octref 👍   Reproduced with 1.42.0-nightly8 on macOS 10.14.6.
