### ISSUE TITLE
Support @use synatax highlighting

### ISSUE THREAD

**Issue by lambert-velir** [atom/language-sass#278]
## Summary

Sass recently launched a new [module system](https://sass-lang.com/blog/the-module-system-is-launched) which includes a new `@use` keyword to import variables, mixins, and functions.  `language-sass` currently does not syntax highlight the `@use` keyword.  

Is this something that can be added to `language-sass`?

**Comment by matteobertoldo** [comment]
@lambert-velir the code was [merged](https://github.com/atom/language-sass/commit/f52ab12f7f9346cc2568129d8c4419bd3d506b47) into `master` but there is no new release for this. @darangi can u plan a new release also for this repo? 🙇🏽‍♂️ 

Thank u so much! 😊

**Comment by xavierfoucrier** [comment]
@darangi @lee-dohm any update on pushing this package on APM?
Thanks for the feedback :wink:

**Comment by darangi** [comment]
Yes @xavierfoucrier.

`language-sass@v0.62.2` has been published 🎉

**Comment by xavierfoucrier** [comment]
Thanks a lot @darangi! :wink:

**Comment by lambert-velir** [comment]
hi @darangi.  

Thanks for updating this!  However, my `language-sass` version is still stuck on `0.62.1` and a new update isn't showing up, even via `apm update`.  Am I missing something?

**Comment by xavierfoucrier** [comment]
@darangi I can confirm, same on my side. May Be this will be published with atom@1.57 ?
