### ISSUE TITLE
Comment issue

### ISSUE THREAD

**Issue by jdsimcoe** [atom/language-sass#46]
When I use `cmd + /` to comment code it wraps the code in `/*  */` instead of using `//` on each line. Is there a way to change this configuration?

**Comment by joseph-turner** [comment]
+1

**Comment by kevinsawicki** [comment]
What language name is shown in the status bar when you see this issue?

I'm having trouble reproducing it using the Sass or SCSS grammars.

**Comment by jdsimcoe** [comment]
`SCSS`. See screenshot below for reference:

![screenshot](https://cloud.githubusercontent.com/assets/275617/6113330/744799e6-b04b-11e4-876d-1ea19e4df29d.png)

**Comment by kevinsawicki** [comment]
Weird, this is what I'm seeing when hitting `cmd-/` in an SCSS file.

![scss-comment](https://cloud.githubusercontent.com/assets/671378/6113413/08e1a6e6-b04c-11e4-8974-bdc5e656acb0.gif)

@jdsimcoe Can you reproduce this when quitting Atom and then running running `atom --safe` to launch it in safe mode?

**Comment by jdsimcoe** [comment]
@kevinsawicki weird. When I run in safe mode it works just fine. What is the best way for me to diagnose what is causing it? My guess is `atom-emmet`.

**Comment by jdsimcoe** [comment]
@kevinsawicki When I disable `atom-emmet` it works fine. Just don't know how to tweak Emmet to not cause this issue.

**Comment by kevinsawicki** [comment]
Okay, closing this out here since it seems definitely seems Emmet related.
