### ISSUE TITLE
Single quote in inline comment breaks highlighting for the rest of the file

### ISSUE THREAD

**Issue by bcherny** [atom/language-sass#53]
![screen shot 2015-03-03 at 2 01 06 pm](https://cloud.githubusercontent.com/assets/1761758/6473353/baa03592-c1ad-11e4-943c-bf52bf30daeb.png)

**Comment by timglorioso** [comment]
Apparently indented syntax doesn't support inline comments yet, so this shouldn't work anyway. See https://github.com/sass/sass/issues/326.
