### ISSUE TITLE
Inconsistent operator coloring

### ISSUE THREAD

**Issue by aar0nr** [atom/language-sass#55]
When you use the addition or subtraction operator with a number, it becomes the same color as the number. The other operators don't do this.

This example is using the Atom Dark syntax theme:

![bug](https://cloud.githubusercontent.com/assets/173250/6887271/790debaa-d617-11e4-807f-21eaaab22efb.png)

**Comment by 50Wliu** [comment]
Cannot reproduce using language-sass@0.47.0; assuming fixed.  Though it seems like the operators aren't even given their own scope, which is a different issue.
