### ISSUE TITLE
Improve support for parentheses in function invocations

### ISSUE THREAD

**Issue by raphinesse** [atom/language-sass#56]
The following is highlighted incorrectly:
```sass
@include foo((bar: $baz));

.foo {
  margin: foo(n 0 (-$foo) 0);
  margin: foo(n 0 (-20px) 0);
}
```

### Atom example
![Atom example](https://cloud.githubusercontent.com/assets/1006620/7008126/fc682208-dc8f-11e4-8801-b1f54018d450.png)

Note how the part in the inner parentheses and the opening inner parenthesis are all highlighted in red here.

### Sublime example
![Sublime example](https://cloud.githubusercontent.com/assets/1006620/7008128/ffa57f24-dc8f-11e4-98e2-68d8644c44f0.png)

Here, the content in the inner parentheses is highlighted as usual.

**Comment by 50Wliu** [comment]
Can you please share a screenshot of how they're supposed to be highlighted (in another editor, eg Sublime or Textmate) and how they're currently highlighted in Atom?  Thanks.

**Comment by raphinesse** [comment]
I updated the issue with additional information.

**Comment by dustindowell22** [comment]
I have some more info! I noticed this just today.

Not correct with parentheses:
![img](http://cl.ly/image/052r2u2v0L2u/Screen%20Shot%202015-09-09%20at%201.45.41%20AM.png)

Correct without parentheses:
![img](http://cl.ly/image/123D2o2L1m0b/Screen%20Shot%202015-09-09%20at%201.46.16%20AM.png)
