### ISSUE TITLE
Comments affect syntax highlighting of first non-empty line below them (indented syntax)

### ISSUE THREAD

**Issue by shaungrady** [atom/language-sass#67]
The syntax highlighting is slightly bugged for the first non-empty line below a comment. See:

![image](https://cloud.githubusercontent.com/assets/52413/8070913/0de674f6-0eba-11e5-832b-7351a3ef354f.png)

Tested with multiple themes, each has issues: Railscast (pictured), Monokai, Atom Dark, and Atom Light.

**Comment by 50Wliu** [comment]
Cannot reproduce using language-sass@0.47.0 and the code example below; assuming fixed.
```sass
// hello, world
$some-variable: 1
```
