### ISSUE TITLE
Sass *.sass files have no auto completion

### ISSUE THREAD

**Issue by genoma** [atom/language-sass#68]
While .scss file extension has auto complete working quite well, working at a couple of projects that use .sass files, I have noticed that there is no auto completion for properties and values.

**Comment by kevinsawicki** [comment]
I believe this has been resolved by https://github.com/atom/autocomplete-css/pull/13

Please comment if you still don't see these in Atom 1.0.3+.

**Comment by genoma** [comment]
It is working indeed, thanks.
