### ISSUE TITLE
nth-child inconsistent coloring when using an+b format

### ISSUE THREAD

**Issue by varemenos** [atom/language-sass#70]
the `n` in the `an+b` format is badly colored.
Here is an example:

![screenshot from 2015-06-23 22-30-29](https://cloud.githubusercontent.com/assets/626343/8315219/b3845c5a-19f7-11e5-9663-17916351fd70.png)

**Comment by batjko** [comment]
Could this be some Linter issue perhaps?
Does it still happen in safe mode (`atom --safe`)?

**Comment by izuzak** [comment]
@batjko Yeah, it's visible in safe mode as well.

```
@media (min-width: 100em) {
  .foo-bar > [class^='column-']:nth-last-child(-n + 2) {
    color: blue;
  }
}
```

Try pasting that in a new file and setting the SCSS grammar (with one dark themes).

**Comment by batjko** [comment]
I don't know how SASS works, but if it helps, it also seems to happen if you replace the n with some other (presumably pre-defined) letter, e.g. m, k, h and l, but not with a, s, q etc.
