### ISSUE TITLE
Support autocomplete for referenced parent selectors

### ISSUE THREAD

**Issue by dmitry** [atom/language-sass#71]
Currently if I write `.plac` it will find only `.place` class name, and not `.place__header`.

```sass
.place {
  &__header {

  }
}
```

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#parent-selector

**Comment by saschagehlich** [comment]
Since sass supports includes / imports, this will be very tricky to implement... something like this is possible in Sass:

```sass
// A.scss
.A {
  @import C
}

// B.scss
.B {
  @import C
}

// C.scss
&__foo {

}
```

**Comment by 50Wliu** [comment]
This issue was moved to atom/autocomplete-css#50
