### ISSUE TITLE
Nested closing selector brackets are not colored

### ISSUE THREAD

**Issue by thomaslindstrom** [atom/language-sass#74]
<img width="504" alt="screen shot 2015-08-27 at 04 34 11" src="https://cloud.githubusercontent.com/assets/2833514/9511280/3acbf952-4c75-11e5-99cc-5315537a0511.png">

```SASS
.Footer {
    background: #000;
    width: 100%;
    text-align: center;
    padding: 34px 0 18px;
    display: block;
    box-sizing: border-box;

    .page--front & {
        @media (min-width: 805px) { display: none; }
    }
}
```

Neither of the two final closing brackets are syntax highlighted.

**Comment by dustindowell22** [comment]
![img](http://cl.ly/image/2Z2Z3s273g1O/Screen%20Shot%202015-08-30%20at%2010.26.44%20AM.png)

I'm not seeing anything, what theme are you using?

**Comment by thomaslindstrom** [comment]
It's not theme dependent. Take a look in attachment 1,

**Comment by patoezequiel** [comment]
Same here, the closing brackets in nested selectors of SCSS are not colored.

![screenshot_6](https://cloud.githubusercontent.com/assets/5291103/13539578/0b7f2038-e230-11e5-905c-7fb393146d17.png)
