### ISSUE TITLE
TypeError: Error linting 

### ISSUE THREAD

**Issue by simpsondigital** [atom/language-sass#76]
Every time I try to save a scss file, I keep getting this error. Used to work fine, so I'm wondering if there was a recent breaking change? Running Mac OS X 10.10.5 Yosemite.

**Comment by mnquintana** [comment]
Can you post the full stack trace of this error here? (When it pops up there should be a copy icon in the notification.) This sounds like an issue with a linter package, though.

**Comment by 50Wliu** [comment]
Closing as this is most likely an issue with a Linter package, and not with language-sass itself.
