### ISSUE TITLE
Wrong syntax highlighting - especially flexbox properties

### ISSUE THREAD

**Issue by andrejkostal** [atom/language-sass#78]
I have tried another Sass syntax highlighter and everything worked just fine. 

![atombug](https://cloud.githubusercontent.com/assets/13579693/9716179/98a2b958-5567-11e5-8aaf-c9d8998ff714.png)

**Comment by 50Wliu** [comment]
Inline code for easy copy/pasting:
```sass
.button-topbar-searchbox
  display: flex
  align-items: center
  justify-content: center
  background-color: #4C8EFB
  color: #fff
  border: 1px solid #3079ED
  border-top-right-radius: 3px
  border-bottom-right-radius: 3px
  width: 40px
  height: 40px
```

**Comment by 50Wliu** [comment]
At this point only `align-items` and `justify-content` aren't recognized.
