### ISSUE TITLE
add navigation to sass/scss @import

### ISSUE THREAD

**Issue by evilebottnawi** [atom/language-sass#94]

**Comment by lee-dohm** [comment]
Please include some more information as to what it is you're looking for. You can refer to the [How Do I Submit a (Good) Enhancement Suggestion?](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion) section of the CONTRIBUTING guide for ideas on what it is that can help us understand what you want.

**Comment by 50Wliu** [comment]
No response, closing.
