### ISSUE TITLE
support for CSS modules (e.g., 'composes' keyword)?

### ISSUE THREAD

**Issue by jeffreywescott** [atom/language-sass#96]
Hi. I'm wondering if it would be easy / desirable to support the [`composes` keyword from CSS-modules](https://github.com/css-modules/css-modules#user-content-dependencies)? Right now, it parses as an error and highlights the word in red.

**Comment by 50Wliu** [comment]
As `composes` is not part of the CSS spec and is instead its own CSS-like language, I don't think language-sass should support this.  Something like `language-css-modules` could though.

Feel free to correct me if I'm misunderstanding something.
