### ISSUE TITLE
negative numbers aren't highlighted correctly

### ISSUE THREAD

**Issue by giladgray** [atom/language-sass#99]
![sass-negatives](https://cloud.githubusercontent.com/assets/464822/12205908/cf59bba4-b5f2-11e5-83e9-83cb18ea0ca9.png)

1. the minus sign in -50% isn't colored the same, because it's not a part of the `constant.numeric`.
2. the -50% in translate() is marked as `variable.parameter.url` which isn't even close to correct.

Shouldn't be much more than adding optional minus sign to numeric regex.

**Comment by mnquintana** [comment]
Confirmed in Atom 1.3.2
